### PR TITLE
initial adding, hot-reloading added

### PR DESCRIPTION
**Pull request by nathandunn**
This explores using mongodb standalone to see if the impact is fairly minimal or not.

### CODE REVIEW

**Comment by nathandunn** [comment]
- https://www.tutorialspoint.com/mongodb/mongodb_create_database.htm
- https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/
- https://docs.mongodb.com/manual/reference/method/db.createUser/

```
use apollo
db.apollo.insert({ "name":"Apollo"})
db.createUser({ user:"apollo-user",pwd:passwordPrompt(),roles:[] })
```

**Comment by nathandunn** [comment]
http://gorm.grails.org/latest/mongodb/manual/

**Comment by rbuels** [comment]
what's the rationale behind exploring mongodb?

**Comment by nathandunn** [comment]
@rbuels  - I was just curious, with minimal work, if I could get the integration tests to pass as mongodb is well supported in Grails.   Just a curious whim.

**Pull request closed without merging**
