### PR TITLE
fix gff3 output test

### LINKED ISSUE #22: fix gff3 output test
```
......S.............SSS.S..................................
----------------------------------------------------------------------
Ran 59 tests in 118.577s

OK (SKIP=5)
```

- [x] IOTest.test_export_gff3

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #22 

Fix IOTest.test_export_gff3:

- [x] missing parent for all
- [x] fix owners for all
- [x] redo query for parent == gene and output handles arbitrary number of children
- [x] fix CDS off by one
- [x] fix dual exon (using parent FL)
- [x] fix non-canonical five (should be a single point) - (using parent FL)
- [x] fix non-canonical three (should be a single point) - (using parent FL)

### CODE REVIEW

**Comment by nathandunn** [comment]
The issue is that when we do the query, we get a perfect graph with 6 genes and mRNAs, 7 exons, and 6 CDS's.  However, the actual results are 21 results:

```
MATCH (o:Organism)-[r:SEQUENCES]-(s:Sequence)-[fl:FEATURELOCATION]-(f:Feature),(f)-[owner:OWNERS]-(u)
WHERE (o.id=51 or o.commonName='test_organism')OPTIONAL MATCH (o)--(s)-[cl:FEATURELOCATION]-(parent:Feature)<-[gfr]-(f) WHERE (o.id=51 or o.commonName='test_organism')OPTIONAL MATCH (o)--(s)-[pl:FEATURELOCATION]-(f)-[fr]->(child:Feature) WHERE (o.id=51 or o.commonName='test_organism') RETURN  {sequence: s, feature:  f,location: fl,children: collect(DISTINCT {location: cl,r1: fr,feature: child,sequence: s}), owners: collect(distinct u),parent:   { location: collect(distinct pl),r2:gfr,feature:parent }}, f.name,count(*)
```

In this case we get 21 rows, but counts of 1, 2, or 5 depending on the row.  The names all seem to be mRNA names except for 1 that is `mrna-name`, but not worried about that.


```
[parent:[r2:relationship<64>, location:[relationship<60>], feature:node<85>], sequence:node<62>, feature:node<84>, children:[[sequence:node<62>, location:relationship<61>, feature:node<85>, r1:relationship<64>]], location:relationship<60>, owners:[node<49>]]
[parent:[r2:relationship<110>, location:[relationship<101>, relationship<101>, relationship<101>, relationship<101>, relationship<101>], feature:node<109>], sequence:node<62>, feature:node<105>, children:[[sequence:node<62>, location:relationship<109>, feature:node<109>, r1:relationship<110>], [sequence:node<62>, location:relationship<109>, feature:node<106>, r1:relationship<103>], [sequence:node<62>, location:relationship<109>, feature:node<108>, r1:relationship<108>], [sequence:node<62>, location:relationship<109>, feature:node<110>, r1:relationship<112>], [sequence:node<62>, location:relationship<109>, feature:node<107>, r1:relationship<105>]], location:relationship<101>, owners:[node<49>, node<49>, node<49>, node<49>, node<49>]]
[parent:[r2:relationship<103>, location:[relationship<101>, relationship<101>, relationship<101>, relationship<101>, relationship<101>], feature:node<106>], sequence:node<62>, feature:node<105>, children:[[sequence:node<62>, location:relationship<102>, feature:node<109>, r1:relationship<110>], [sequence:node<62>, location:relationship<102>, feature:node<106>, r1:relationship<103>], [sequence:node<62>, location:relationship<102>, feature:node<108>, r1:relationship<108>], [sequence:node<62>, location:relationship<102>, feature:node<110>, r1:relationship<112>], [sequence:node<62>, location:relationship<102>, feature:node<107>, r1:relationship<105>]], location:relationship<101>, owners:[node<49>, node<49>, node<49>, node<49>, node<49>]]
[parent:[r2:relationship<108>, location:[relationship<101>, relationship<101>, relationship<101>, relationship<101>, relationship<101>], feature:node<108>], sequence:node<62>, feature:node<105>, children:[[sequence:node<62>, location:relationship<107>, feature:node<109>, r1:relationship<110>], [sequence:node<62>, location:relationship<107>, feature:node<106>, r1:relationship<103>], [sequence:node<62>, location:relationship<107>, feature:node<108>, r1:relationship<108>], [sequence:node<62>, location:relationship<107>, feature:node<110>, r1:relationship<112>], [sequence:node<62>, location:relationship<107>, feature:node<107>, r1:relationship<105>]], location:relationship<101>, owners:[node<49>, node<49>, node<49>, node<49>, node<49>]]
[parent:[r2:relationship<112>, location:[relationship<101>, relationship<101>, relationship<101>, relationship<101>, relationship<101>], feature:node<110>], sequence:node<62>, feature:node<105>, children:[[sequence:node<62>, location:relationship<111>, feature:node<109>, r1:relationship<110>], [sequence:node<62>, location:relationship<111>, feature:node<106>, r1:relationship<103>], [sequence:node<62>, location:relationship<111>, feature:node<108>, r1:relationship<108>], [sequence:node<62>, location:relationship<111>, feature:node<110>, r1:relationship<112>], [sequence:node<62>, location:relationship<111>, feature:node<107>, r1:relationship<105>]], location:relationship<101>, owners:[node<49>, node<49>, node<49>, node<49>, node<49>]]
[parent:[r2:relationship<105>, location:[relationship<101>, relationship<101>, relationship<101>, relationship<101>, relationship<101>], feature:node<107>], sequence:node<62>, feature:node<105>, children:[[sequence:node<62>, location:relationship<104>, feature:node<109>, r1:relationship<110>], [sequence:node<62>, location:relationship<104>, feature:node<106>, r1:relationship<103>], [sequence:node<62>, location:relationship<104>, feature:node<108>, r1:relationship<108>], [sequence:node<62>, location:relationship<104>, feature:node<110>, r1:relationship<112>], [sequence:node<62>, location:relationship<104>, feature:node<107>, r1:relationship<105>]], location:relationship<101>, owners:[node<49>, node<49>, node<49>, node<49>, node<49>]]
[parent:[r2:relationship<106>, location:[relationship<100>], feature:node<105>], sequence:node<62>, feature:node<104>, children:[[sequence:node<62>, location:relationship<101>, feature:node<105>, r1:relationship<106>]], location:relationship<100>, owners:[node<49>]]
[parent:[r2:relationship<94>, location:[relationship<90>], feature:node<100>], sequence:node<62>, feature:node<99>, children:[[sequence:node<62>, location:relationship<91>, feature:node<100>, r1:relationship<94>]], location:relationship<90>, owners:[node<49>]]
[parent:[r2:relationship<74>, location:[relationship<70>], feature:node<90>], sequence:node<62>, feature:node<89>, children:[[sequence:node<62>, location:relationship<71>, feature:node<90>, r1:relationship<74>]], location:relationship<70>, owners:[node<49>]]
[parent:[r2:relationship<84>, location:[relationship<80>], feature:node<95>], sequence:node<62>, feature:node<94>, children:[[sequence:node<62>, location:relationship<81>, feature:node<95>, r1:relationship<84>]], location:relationship<80>, owners:[node<49>]]
[parent:[r2:relationship<66>, location:[relationship<61>, relationship<61>], feature:node<87>], sequence:node<62>, feature:node<85>, children:[[sequence:node<62>, location:relationship<65>, feature:node<87>, r1:relationship<66>], [sequence:node<62>, location:relationship<65>, feature:node<86>, r1:relationship<63>]], location:relationship<61>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<63>, location:[relationship<61>, relationship<61>], feature:node<86>], sequence:node<62>, feature:node<85>, children:[[sequence:node<62>, location:relationship<62>, feature:node<87>, r1:relationship<66>], [sequence:node<62>, location:relationship<62>, feature:node<86>, r1:relationship<63>]], location:relationship<61>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<83>, location:[relationship<81>, relationship<81>], feature:node<96>], sequence:node<62>, feature:node<95>, children:[[sequence:node<62>, location:relationship<82>, feature:node<96>, r1:relationship<83>], [sequence:node<62>, location:relationship<82>, feature:node<97>, r1:relationship<86>]], location:relationship<81>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<86>, location:[relationship<81>, relationship<81>], feature:node<97>], sequence:node<62>, feature:node<95>, children:[[sequence:node<62>, location:relationship<85>, feature:node<96>, r1:relationship<83>], [sequence:node<62>, location:relationship<85>, feature:node<97>, r1:relationship<86>]], location:relationship<81>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<121>, location:[relationship<117>, relationship<117>], feature:node<115>], sequence:node<62>, feature:node<113>, children:[[sequence:node<62>, location:relationship<120>, feature:node<115>, r1:relationship<121>], [sequence:node<62>, location:relationship<120>, feature:node<114>, r1:relationship<119>]], location:relationship<117>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<119>, location:[relationship<117>, relationship<117>], feature:node<114>], sequence:node<62>, feature:node<113>, children:[[sequence:node<62>, location:relationship<118>, feature:node<115>, r1:relationship<121>], [sequence:node<62>, location:relationship<118>, feature:node<114>, r1:relationship<119>]], location:relationship<117>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<122>, location:[relationship<116>], feature:node<113>], sequence:node<62>, feature:node<112>, children:[[sequence:node<62>, location:relationship<117>, feature:node<113>, r1:relationship<122>]], location:relationship<116>, owners:[node<49>]]
[parent:[r2:relationship<73>, location:[relationship<71>, relationship<71>], feature:node<91>], sequence:node<62>, feature:node<90>, children:[[sequence:node<62>, location:relationship<72>, feature:node<91>, r1:relationship<73>], [sequence:node<62>, location:relationship<72>, feature:node<92>, r1:relationship<76>]], location:relationship<71>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<76>, location:[relationship<71>, relationship<71>], feature:node<92>], sequence:node<62>, feature:node<90>, children:[[sequence:node<62>, location:relationship<75>, feature:node<91>, r1:relationship<73>], [sequence:node<62>, location:relationship<75>, feature:node<92>, r1:relationship<76>]], location:relationship<71>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<93>, location:[relationship<91>, relationship<91>], feature:node<101>], sequence:node<62>, feature:node<100>, children:[[sequence:node<62>, location:relationship<92>, feature:node<101>, r1:relationship<93>], [sequence:node<62>, location:relationship<92>, feature:node<102>, r1:relationship<96>]], location:relationship<91>, owners:[node<49>, node<49>]]
[parent:[r2:relationship<96>, location:[relationship<91>, relationship<91>], feature:node<102>], sequence:node<62>, feature:node<100>, children:[[sequence:node<62>, location:relationship<95>, feature:node<101>, r1:relationship<93>], [sequence:node<62>, location:relationship<95>, feature:node<102>, r1:relationship<96>]], location:relationship<91>, owners:[node<49>, node<49>]]
```

**Comment by nathandunn** [comment]
For each of the 21 rows (with a JSON output):

1. parent feature is mrna-name-00001, feature name is mrna-name and its only child is mrna-name-0001 . . not sure if parent is used . . odd, but a definite error.   However, the parent feature should be mrna-name (the gene).
1. parent name feature is `Merlin_3_mRNA-00001` . . while the feature itself is the gene (Merlin_3_mRNA)
1. parent is an exon, while the feature itself is a transcript (mrna-name-0001)
1. parent is a CDS, and the feature type is a transcript
1. parent name feature is ``Merlin_4_mRNA-00001` is a transcript, while the feature is a gene
1. parent is a CDS, and the feature type is a transcript
1. parent is exon, and the feature type is a transcript
1. parent is a transcript, but the feature is a gene, so the children are transcripts
1. parent is a CDS, and the feature type is a transcript
... etc. 

For most of these, the children are calculated correctly (one level).  But parent is never a gene. 

So it looks like parent is ALWAYS wrong and feature is sometimes a gene and sometimes a transcript.  

Looked like the gene relationship was pointing in the wrong direction.

**Comment by nathandunn** [comment]
@deepakunni3  (and self) FYI, solution was explicitly using the neo4j labels to determine type instead of the hydrated GORM class, which was for some reason incorrect.

**Comment by deepakunni3** [comment]
Not sure what "hydrate" means here. I am assuming that the GORM was using different labels at random and hence the separate results as response?

**Comment by nathandunn** [comment]
@deepakunni3  yeah, it looked like it was sharing a reference for one of the cast features, it was very weird

**Pull request merged**
